name: xmonad-phenax-config
version: 0.0.0
license: MIT
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib

executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wdefault
      - -Wextra
      - -Wno-unused-do-bind
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
